### ISSUE TITLE
add '-n' option

### ISSUE THREAD

**Issue by leissa** [dsoprea/GDriveFS#129]
Hi,

I'm on archlinux. Apperantly, systemd appends to all mount commands -n during boot. So putting gdfs in the fstab causes this error:

Mär 29 23:39:25 c64 mount[294]: usage: mount.gdfs [-h] [-d] [-o OPT] auth_storage_file mountpoint
Mär 29 23:39:25 c64 mount[294]: mount.gdfs: error: unrecognized arguments: -n
Mär 29 23:39:25 c64 systemd[1]: mnt-gdrive.mount mount process exited, code=exited status=2

If you add the line of the README after boot, everything works fine. I guess, just adding a dummy option "-n" would do the trick.

**Comment by dsoprea** [comment]
This doesn't sound right to me. Can you provide documentation of this
requirement in SystemD/Arch?

**Comment by leissa** [comment]
see:
https://bbs.archlinux.org/viewtopic.php?pid=1515718#p1515718

short answer:
-sfnv is mandatory for external helpers. see mount mount man page under external helpers.
