### ISSUE TITLE
temp files remaining

### ISSUE THREAD

**Issue by calisro** [dsoprea/GDriveFS#135]
I use rsync to sync a local fs to gdrive.  It sometimes has a lot of jpegs/mpwgs to sync.  What I am finding is its filling my tmp drive as it is leaving very large temp files after each transfer.  This breaks my transfer as it fills tmp. I need to clean it up and restart it.

Shouldnt these be cleaned up after each transfer? 

It would also be good to be able to specify a different temp location as well as my tmp is only 8GB since its a tempfs fs using memory.  That is a secondary problem though as that preventa any transfer over 8GB. :(

**Comment by dsoprea** [comment]
Closing this issue since #137 (which is more recent, but also more active) and #117 cover both of these things.
