### ISSUE TITLE
won't to install on Rasbian

### ISSUE THREAD

**Issue by stanelie** [dsoprea/GDriveFS#138]
Hello.

So, I am trying to install on the latest Rasbian on a raspberry pi. 

I installed "python-dev", "python-pip", then I ran "pip install gdrivefs" and then I tried to run "gdfstool auth -u", got some error about dates, installed "python-dateutil", ran "gdfstool auth -u" again and it now fails with "File "/usr/local/bin/gdfstool", line 15, in <module>
    import gdrivefs.gdfs.gdfuse" and some more errors...

So, it looks like I might be missing some dependencies, but the does not list the dependencies.

Thoughts? Thanks!

**Comment by dsoprea** [comment]
Not enough information. Please show what you're running and the output. Closing for now.
