### ISSUE TITLE
Will not mount on boot from fstab

### ISSUE THREAD

**Issue by danielunderwood** [dsoprea/GDriveFS#141]
Drive will not mount on boot. The entry in `/etc/fstab` is the following:

```
/var/cache/gdfs.creds /mnt/Google-Drive gdfs    allow_other     0       0 
```

My other disks mount correctly and strangely, if I drop to a shell when the error occurs at boot and use `mount -a`, it will mount correctly.

I'm using I am using Ubuntu 14.04.3 LTS with kernel 3.13.0-62-generic.

**Comment by blha303** [comment]
@dsoprea Kinda important, readme probably needs to be changed, fstab is processed before networking starts and it stops the OS from loading. I had this issue yesterday, after setting up GDriveFS and adding to fstab, computer wouldn't reboot, had to boot in recovery mode to remove the line from fstab

**Comment by n-st** [comment]
@danielunderwood @blha303 Have you tried adding `_netdev` to the mount options in the `fstab`?

>**_netdev**
 The filesystem resides on a device that requires network access (used to prevent the system from attempting to mount these filesystems until the network has been enabled on the system).


You can also add `nofail` to continue booting even if the filesystem can't be mounted.

**Comment by d0m1nation** [comment]
Had the same issue. Added `_netdev`. It boots now but still fails to mount. 
```
Dec 28 21:57:20 pipes mount[434]: File "/sbin/mount.gdfs", line 47, in <module>
Dec 28 21:57:20 pipes mount[434]: main()
Dec 28 21:57:20 pipes mount[434]: File "/sbin/mount.gdfs", line 44, in main
Dec 28 21:57:20 pipes mount[434]: option_string=option_string)
Dec 28 21:57:20 pipes mount[434]: File "/usr/lib/python2.7/site-packages/gdrivefs/gdfs/gdfuse.py", line 897, in mount
Dec 28 21:57:20 pipes mount[434]: **fuse_opts)
Dec 28 21:57:20 pipes mount[434]: File "/usr/lib/python2.7/site-packages/fuse.py", line 399, in __init__
Dec 28 21:57:20 pipes mount[434]: raise RuntimeError(err)
Dec 28 21:57:20 pipes mount[434]: RuntimeError: 1
Dec 28 21:57:20 pipes systemd[1]: mnt-gdrive.mount: Mount process exited, code=exited status=1
Dec 28 21:57:20 pipes systemd[1]: Failed to mount /mnt/gdrive.
Dec 28 21:57:20 pipes systemd[1]: Dependency failed for Remote File Systems.
Dec 28 21:57:20 pipes systemd[1]: remote-fs.target: Job remote-fs.target/start failed with result 'dependency'.
Dec 28 21:57:20 pipes systemd[1]: mnt-gdrive.mount: Unit entered failed state.
```

**Comment by naumenko-sa** [comment]
Finally on Fedora 22 I'm not using fstab to mount gdrive. 
I have created a script to mount after the network interface is up.
/etc/NetworkManager/dispatcher.d/40-mount-gdrive
```
#!/bin/bash
if [ "$2" = "up" ];then
    mount /var/cache/gdfs.creds /home/sergey/googledrive -t gdfs -o allow_other
fi
```
To unmount:
/etc/NetworkManager/dispatcher.d/pre-down.d/40-umount-gdrive
```
#!/bin/bash
umount /home/sergey/googledrive
```

**Comment by dsoprea** [comment]
Thanks for mentioning. Done.
