### ISSUE TITLE
sudo pip install gdrivefs failed at gevent install

### ISSUE THREAD

**Issue by yohannmonnier** [dsoprea/GDriveFS#150]
sudo pip install gdrivefs                                                                                                                                                                          
Password:

The directory '/Users/yohann/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/yohann/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gdrivefs
  Downloading gdrivefs-0.14.2.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): fusepy==2.0.2 in /Library/Python/2.7/site-packages (from gdrivefs)
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 267kB/s
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
Requirement already satisfied (use --upgrade to upgrade): google-api-python-client==1.2 in /Library/Python/2.7/site-packages (from gdrivefs)
Requirement already satisfied (use --upgrade to upgrade): greenlet==0.4.2 in /Library/Python/2.7/site-packages (from gdrivefs)
Requirement already satisfied (use --upgrade to upgrade): httplib2==0.8 in /Library/Python/2.7/site-packages (from gdrivefs)
Collecting python-dateutil==2.2 (from gdrivefs)
  Downloading python-dateutil-2.2.tar.gz (259kB)
    100% |████████████████████████████████| 262kB 1.0MB/s
Collecting six==1.7.3 (from gdrivefs)
  Downloading six-1.7.3-py2.py3-none-any.whl
Installing collected packages: gevent, gipc, six, python-dateutil, gdrivefs
  Running setup.py install for gevent
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-glkUv4/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jDesmp-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-intel-2.7
    creating build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/__init__.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/_threading.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/backdoor.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/baseserver.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/coros.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/event.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/fileobject.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/greenlet.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/hub.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/local.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/lock.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/monkey.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/os.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/pool.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/pywsgi.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/queue.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/resolver_ares.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/resolver_thread.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/select.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/server.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/socket.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/ssl.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/subprocess.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/thread.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/threading.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/threadpool.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/timeout.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/util.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/win32util.py -> build/lib.macosx-10.11-intel-2.7/gevent
    copying gevent/wsgi.py -> build/lib.macosx-10.11-intel-2.7/gevent
    running build_ext
    Running '/bin/sh /private/tmp/pip-build-glkUv4/gevent/libev/configure > configure-output.txt' in /private/tmp/pip-build-glkUv4/gevent/build/temp.macosx-10.11-intel-2.7/libev
    building 'gevent.core' extension
    creating build/temp.macosx-10.11-intel-2.7/gevent
    cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -U__llvm__ -arch i386 -arch x86_64 -pipe -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CHECK_ENABLE=0 -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.11-intel-2.7/libev -Ilibev -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.11-intel-2.7/gevent/gevent.core.o
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    libev/ev.c:467:48: warning: '/*' within block comment [-Wcomment]
    /*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                                   ^
    libev/ev.c:935:42: error: '_Noreturn' keyword must precede function declarator
      ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                             ^~~~~~~~~~~~
      _Noreturn
    libev/ev.c:738:26: note: expanded from macro 'ecb_noreturn'
      #define ecb_noreturn   _Noreturn
                             ^
    libev/ev.c:1311:31: warning: 'extern' variable has an initializer [-Wextern-initializer]
      EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                                  ^
    libev/ev.c:1482:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1493:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:1620:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2168:
    libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    In file included from gevent/gevent.core.c:302:
    In file included from gevent/libev.h:2:
    In file included from libev/ev.c:2174:
    libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
          array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
          ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:3332:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                           ~~~~~~~~~~^~~~~~~~~~~~~ ~
    libev/ev.c:3332:34: note: place parentheses around the '&' expression to silence this warning
      fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                     ^
                           (                      )
    libev/ev.c:3371:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4041:5: warning: unused variable 'ocur_' [-Wunused-variable]
        array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
        ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4081:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4266:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    libev/ev.c:4349:3: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
      ^
    libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
          int ecb_unused ocur_ = (cur);                                     \
                         ^
    13 warnings and 1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-glkUv4/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jDesmp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-glkUv4/gevent

**Comment by HammyHavoc** [comment]
Having this issue myself.

**Comment by stanelie** [comment]
Same here, cannot install...

**Comment by stanelie** [comment]
Got it : missing dependencies
I did `sudo apt-get install python-dev libxml2-dev libxslt-dev` and the installer was able to finish this time. Not sure if the libs were required or not.

It would be nice if the readme included the required dependencies.

**Comment by dsoprea** [comment]
Closing this issue. If you continue to have to problem, raise an issue with the *gevent* team.
