### ISSUE TITLE
feature request: support for multiple google accounts

### ISSUE THREAD

**Issue by bedros** [dsoprea/GDriveFS#152]
I could not find a way to use gdrivefs with multiple google accounts

can I mount it like this

guser1 at /mnt/guser1
guser2 at /mnt/guser2

I'm not sure is the cache is shared or how it would work in such a case.

Thanks

Bedros

**Comment by chadberg** [comment]
I've been able to do it by setting up two credentials files and calling them explicitly when mounting. This is pretty easy if you mount using the gdfstool

**Comment by tukoz** [comment]
Hum, nice find! I'll try the multi credential files.

**Comment by dsoprea** [comment]
I'm closing this ticket. @chadberg is using the suggested strategy.
