### ISSUE TITLE
UTF-8 File names fail with IO-Error

### ISSUE THREAD

**Issue by sebastian-philipp** [dsoprea/GDriveFS#153]
```
$ LANG=C touch äöü
touch: cannot touch '\303\244\303\266\303\274': Input/output error
```
This was a bit disappointing.

**Comment by stanelie** [comment]
Same thing for me. I use french accented characters and they appear as garbage, and the file attributes of these files is not readable.

![2016-03-08 12_09_04-root owncloud1_ _media_gdrivefs_887_captations_vancouver](https://cloud.githubusercontent.com/assets/2935029/13609352/9a3032b0-e526-11e5-8f9f-832b90c65460.png)

**Comment by dsoprea** [comment]
This instance has been fixed. Let me know if you see it anywhere else. Sorry for the inconvenience and the delay.
