### ISSUE TITLE
python3 migration

### ISSUE THREAD

**Issue by je-vv** [dsoprea/GDriveFS#167]
Wondering if possible to migrate to python3 as the dependencies are available for python3 as well.  On a 1st trial, besides the oaut2 lib patch (see issue https://github.com/dsoprea/GDriveFS/issues/166), the following patch for httplib is also required:

`diff -Naur GDriveFS-0.14.8-old/gdrivefs/gdtool/drive.py GDriveFS-0.14.8/gdrivefs/gdtool/drive.py`
`--- GDriveFS-0.14.8-old/gdrivefs/gdtool/drive.py   2016-11-10 11:38:48.477494868 -0600`
`+++ GDriveFS-0.14.8/gdrivefs/gdtool/drive.py 2016-11-10 11:41:13.914160628 -0600`
`@@ -4,7 +4,7 @@`
` import random`
` import json`
` import time`
`-import httplib`
`+import http.client`
` import ssl `
` import tempfile`
` import pprint`
`@@ -54,7 +54,7 @@`
`         for n in range(0, 5): `
`             try:`
`                 return f(*args, **kwargs)`
`-            except (ssl.SSLError, httplib.BadStatusLine) as e:`
`+            except (ssl.SSLError, http.client.BadStatusLine) as e:`
`                 # These happen sporadically. Use backoff.`
`                 _logger.exception("There was a transient connection "`
`                                   "error (%s). Trying again [%s]: %s",`

But that's not all.  Some python3 libraries have changed substantially, therefore, there errors to be solved like:

> ...
>   File "/usr/lib/python3.5/tempfile.py", line 483, in func_wrapper
>     return func(*args, **kwargs)
> TypeError: a bytes-like object is required, not 'str'

So, more fixes are required...

**Comment by GreyAlien502** [comment]
I believe i have made all the changes necessary to move this project to python 3 (3.6).
I have tested it out by using all the features, but i'm not sure what unit tests would be useful here.

**Comment by dsoprea** [comment]
Merged.
