### ISSUE TITLE
Using with a proxy?

### ISSUE THREAD

**Issue by lorenzosu** [dsoprea/GDriveFS#191]
Hi,
I've tried using gdfs behind a proxy and it seems to hang. I tried both by setting environment http_proxy https_proxy etc. and with proxychains.
Any idea if this is feasible and what I would look into?

Thanks!
Lorenzo.

**Comment by dsoprea** [comment]
You haven't provided any logs or information about what you've been doing.

It's all HTTP communication with the possible exception of actual file
transfer, but you need to provide more information. Even then, this issue
has never been reported before.

**Comment by lorenzosu** [comment]
Hi @dsoprea thanks for your answer.

So I tried now setting *all* environment variables for getting the proxy (squid with authentication) to work namely http_proxy https_proxy ftp_proxy rsync_proxy and all upper-case equivalents worked by doing:

`gdfs -o allow_other default Documents/GDrive`

in a terminal where these were all set through a script

**Comment by lorenzosu** [comment]
Hi @dsoprea thanks for your answer.

So I tried now setting *all* environment variables for getting the proxy (squid with authentication) to work namely http_proxy https_proxy ftp_proxy rsync_proxy and all upper-case equivalents worked by doing:

`gdfs -o allow_other default Documents/GDrive`

in a terminal where these were all set through a script

**Comment by blueswill** [comment]
I have the same problem. In China Google has been banned so I must use one proxy to connect Google Drive. Mounting the fs by command `proxychains -q gdfs -o allow_other .gdrive GoogleDrive` is successful. However, when I touch the file in GoogleDrive directory it hangs. I am not familiar with fuse so I have no idea about it.
