### ISSUE TITLE
AuthorizationFailureError with SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Masterxilo** [dsoprea/GDriveFS#198]
I ran `gdfstool auth --url`, visited the URL, got the auth code, then I did this:

```
$ gdfstool auth --auth ~/gdfs.credentials2 4/AAC_Cy8Q-wboFTYzpV---REST-OMITTED---      
Traceback (most recent call last):
  File "/usr/local/bin/gdfstool", line 125, in <module>
    main()
  File "/usr/local/bin/gdfstool", line 118, in main
    _handle_auth(args)
  File "/usr/local/bin/gdfstool", line 56, in _handle_auth
    _handle_auth_store(*args.auth)
  File "/usr/local/bin/gdfstool", line 50, in _handle_auth_store
    authorize.step2_doexchange(authcode)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/oauth_authorize.py", line 143, in step2_doexchange
    raise AuthorizationFailureError(message)
gdrivefs.errors.AuthorizationFailureError: Could not do auth-exchange (this was either a legitimate error, or the auth-exchange was attempted when not necessary): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

What am I doing wrong?

**Comment by asreimer** [comment]
I have also encountered this error.

**Comment by d3stusi** [comment]
@asreimer I followed your instructions but when running auth_get_url i'm getting an error saying gdfstool command is not found.  Tried executing from a few different directories down to the resources/scripts one from GdriveFS but still no luck.  Same message for gdfs default mnt/googledrive/

**Comment by pantegra** [comment]
I have followed you instructions on getting the gdfstools installed.  This is what I get now.  
pi@raspberrypi:~ $ gdfstool auth_get_url
Traceback (most recent call last):
  File "/usr/local/bin/gdfstool", line 15, in <module>
    import gdrivefs.gdfs.gdfuse
ImportError: No module named gdfs.gdfuse
For some reason the import is not picking up all the items in the module.  From the python command line I imported the gdrivefs module and ran a dir() on the object to find out what attributes are on that module  This is what is reported back.  
>>> import gdrivefs.gdfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gdfs
>>> dir(gdrivefs)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__']
>>> 
There is diffidently some link missing somewhere in the new scripts.  
 python 
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.

**Comment by pantegra** [comment]
Well i got the system to work, kinda.  This is what I am getting now.
pi@raspberrypi:~ $ sudo gdfstool auth -a /home/pi/gdfs.creds "{MY code}"
Traceback (most recent call last):
  File "/usr/local/bin/gdfstool", line 125, in <module>
    main()
  File "/usr/local/bin/gdfstool", line 118, in main
    _handle_auth(args)
  File "/usr/local/bin/gdfstool", line 56, in _handle_auth
    _handle_auth_store(*args.auth)
  File "/usr/local/bin/gdfstool", line 50, in _handle_auth_store
    authorize.step2_doexchange(authcode)
  File "/usr/local/lib/python2.7/dist-packages/gdrivefs/gdtool/oauth_authorize.py", line 143, in step2_doexchange
    raise AuthorizationFailureError(message)
gdrivefs.errors.AuthorizationFailureError: Could not do auth-exchange (this was either a legitimate error, or the auth-exchange was attempted when not necessary): invalid_grantBad Request

Any thoughts

**Comment by dsoprea** [comment]
Looks like you have a local issue with your installed libraries. I also just adjusted some dependency versions. You might want to try it again, but it might be better, at least for experimentation, to use virtualenv, which is a sandbox that gives you the ability to ignore anything else that might already be installed on your system.

Try testing with this if/when you have virtualenv installed:

```

**Comment by dsoprea** [comment]
I'm gonna close this issue for now since the project is fine.
