### ISSUE TITLE
sudo pip install gdrivefs fails

### ISSUE THREAD

**Issue by thissophie** [dsoprea/GDriveFS#47]
On OS X Mountain Lion. I don't even remotely know enough about python to figure it out!

<pre>
Grace:GDriveFS patrick$ sudo pip install gdrivefs
Downloading/unpacking gdrivefs
  Running setup.py egg_info for package gdrivefs
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/gdrivefs/setup.py", line 9, in <module>
        from gdrivefs import tools
      File "gdrivefs/__init__.py", line 1, in <module>
        from gdrivefs import log_config
      File "gdrivefs/log_config.py", line 12, in <module>
        log_syslog = SysLogHandler('/dev/log', facility=SysLogHandler.LOG_LOCAL0)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 730, in __init__
        self._connect_unixsocket(address)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 746, in _connect_unixsocket
        self.socket.connect(address)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
        return getattr(self._sock,name)(*args)
    socket.error: [Errno 2] No such file or directory
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build/gdrivefs/setup.py", line 9, in <module>

    from gdrivefs import tools

  File "gdrivefs/__init__.py", line 1, in <module>

    from gdrivefs import log_config

  File "gdrivefs/log_config.py", line 12, in <module>

    log_syslog = SysLogHandler('/dev/log', facility=SysLogHandler.LOG_LOCAL0)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 730, in __init__

    self._connect_unixsocket(address)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 746, in _connect_unixsocket

    self.socket.connect(address)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth

    return getattr(self._sock,name)(*args)

socket.error: [Errno 2] No such file or directory

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build/gdrivefs
Storing complete log in /Users/patrick/Library/Logs/pip.log
Grace:GDriveFS patrick$ 
</pre>

**Comment by dany20mh** [comment]
@dsoprea I have this problem also and can't get around it anyway.

```
The directory '/Users/danial/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/danial/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 861kB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 581kB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-pvdtdadh/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-pvdtdadh/gipc/
```

**Comment by dsoprea** [comment]
This issue is four year old and a completely different issue. Please create a new issue in the future.

Pay more attention to the error message:

"The directory '/Users/danial/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory."

Delete your cache directory. You probably previously tried to use`pip` to install something as root.

**Comment by dany20mh** [comment]
I deleted the whole folder and I still not able to get it, I even tried it without sudo too and it won't work, it create a pip folder inside the caches but nothing happens.

```
Danials-iMac:~ danial$ cd /Users/danial/Library/Caches/pip
-bash: cd: /Users/danial/Library/Caches/pip: No such file or directory
Danials-iMac:~ danial$ sudo pip install gdrivefs
The directory '/Users/danial/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/danial/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 3.0MB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-famsb5gi/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-famsb5gi/gipc/
Danials-iMac:~ danial$ pip install gdrivefs
Collecting gdrivefs
  Downloading gdrivefs-0.14.8.tar.gz (67kB)
    100% |████████████████████████████████| 71kB 3.5MB/s 
Collecting fusepy==2.0.2 (from gdrivefs)
  Downloading fusepy-2.0.2.tar.gz
Collecting gevent==1.0 (from gdrivefs)
  Downloading gevent-1.0.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.1MB/s 
Collecting gipc==0.4.0 (from gdrivefs)
  Downloading gipc-0.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-988qsg8h/gipc/setup.py", line 22, in <module>
        long_description=open("README.rst").read().decode('utf-8'),
    AttributeError: 'str' object has no attribute 'decode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h7/9mtx2w996rvbrp0jhbf_52c00000gn/T/pip-build-988qsg8h/gipc/
Danials-iMac:~ danial$ 
```

**Comment by dsoprea** [comment]
Please repost as new issue.
